# Introduction

The World Development Indicators (WDI) serve as a premier source for development data, widely used by governments, researchers, journalists, and the public to understand and track important development questions. Starting as a small set of tables in the annex of the 1978 World Development Report, the WDI has grown to encompass over 1,400 indicators covering 217 economies going back to 1960. In 2010, it became available as an open, online database.

The World Development Indicators (WDI) improve the utility of data by offering a dependable, comprehensive, and readily accessible collection of indicators of development. The standing of the WDI as a premier repository of developmental data is underpinned by the high quality of its underlying data sources. Drawing from a diverse array of providers, including the World Bank, national statistical offices, United Nations agencies, research institutions, academic entities, and private sector contributors, the WDI excels in amalgamating data from multiple sources. This integration facilitates seamless navigation and interaction among a wide spectrum of development topics, enhancing the user experience and research capabilities.

The WDI strives to meet the needs of different users, including, for example, economists, public health specialists, environment specialists and others. Maintaining the WDI's reputation as a premier source of data requires that the WDI offers a broad high quality and relevant set of indicators for the community that uses them. This document aims to provide clarity to users on what standards are used to include (or to occasionally remove) indicators in the WDI.[^1]


Traditionally, the World Development Indicators (WDI) have been assessed, by the WDI Team, using a set of dimensions that are widely recognized in global statistical frameworks. Fantom and Khokhar (2014) encapsulated these dimensions as relevance, openness, accuracy, comparability, and coverage. Historically, these criteria have been effective for WDI, but they had not been organized into a detailed framework that allows for a quantifiable and structured choice and evaluation process. In response, the WDI team has introduced a revised framework, inspired by Jolliffe et al. (2023) and the 2021 World Development Report: Data for Better Lives and aligned with the principles outlined in the <span style="color: #0275d8;">World Bank Development Data Quality Policy</span>.[^2] This new framework introduces four pivotal conditions for data utility in development contexts: ease of use, safety, comprehensive coverage, and high quality. The original dimensions of relevance, openness, accuracy, comparability, and coverage are now integrated into this new framework, along with several added criteria.

The aim of this updated framework is to refine the WDI indicator selection process, ensuring it is both methodically structured and in harmony with established statistical principles and contemporary best practices. The revised framework introduces a set of metrics designed to evaluate and select indicators for the World Development Indicators (WDI). Certain metrics are quantifiable, such as the number of countries covered or the time span of data availability. Other metrics, like the quality of an indicator and its relevance to development, require qualitative assessment. The inclusion or exclusion of an indicator in the WDI hinges on a balanced consideration of these quantitative and qualitative metrics and the trade-offs they present. To provide transparency in our indicator selection process, these criteria are made available to the public on the WDI website.

[^1]: Removed indicators can be accessed at the <a href="https://datatopics.worldbank.org/world-development-indicators/wdi-archives.html" target="_blank">WDI archives </a>.
[^2]: A mapping between the WDI criteria framework and the World Bank Development Data Quality Policy is available in Annex Table A3.
